-- 학생 테이블 생성
-- 학번, 이름, 학과명, 평점
CREATE TABLE STUDENT(
	STD_NO CHAR(8), --()안에 있는 숫자 ; 8바이트
	STD_NAME VARCHAR2(50), -- 고정길이 문자열을 사용
	MAJOR_NAME VARCHAR2(50),
	STD_SCORE NUMBER(3,2) -- 숫자 3자리, 소수점 2자리까지 사용
	);
	
-- 데이터 추가
INSERT INTO STUDENT(STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES('20240001', '김창수', '기계설계', 3.55);

INSERT INTO STUDENT(STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES('20240002', '정지영', '건축설계', 3.85);

INSERT INTO STUDENT(STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES('20240003', '김철수', '컴퓨터공학', 3.25);

INSERT INTO STUDENT(STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES('20240004', '장미희', '산업디자인', 3.85);

-- 학생 테이블의 데이터 전체 조회
SELECT * FROM STUDENT;
-- 데이터 부분 조회(학번, 이름)
SELECT STD_NO, STD_NAME FROM STUDENT;


-- DDL ; DATA DEFINITION LANGUAGE ; 데이터 정의어 OR SQL 명령어
-- 테이블 생성
CREATE TABLE 테이블 이름(
	컴럼명1 테이터타입 [NULL | NOT NULL], -- NULL ; 입력 안해도 됨, NOT NULL ; 입력해야함
	컴럼명2 테이터타입 DEFAULT 기본값,
	컴럼명3 테이터타입 ,
	...
	CONSTRAINT 제약조건 이름 PRIMARY KEY(컬럼명) -- 주 식별자 설정시 사용
	-- 기본 키(Primary Key), 외래 키(Foreign Key) 자주 사용함
);

-- 데이터 타입
-- 문자열 ; char(2000바이트), varchar2(4000바이트), clob(128테라바이트)
-- 숫자열 ; number(자리수, 소수점 개수)최대 38자리, float(128)
-- 날짜 시간 ; date(날짜/시간), timestamp(소수점가지 저장 가능 최대 9자리)


-- PERSON 테이블
-- 이름 ; 문자열
-- 나이 ; 숫자
CREATE TABLE PERSON(
	PNAME VARCHAR2(30),
	PAGE NUMBER(3)
	
);
-- 데이터 5건 추가하는 sql문
INSERT INTO PERSON(PNAME, PAGE) VALUES('창수',38);
INSERT INTO PERSON(PNAME, PAGE) VALUES('지영',39);
INSERT INTO PERSON(PNAME, PAGE) VALUES('원광',28);
INSERT INTO PERSON(PNAME, PAGE) VALUES('철수',31);
INSERT INTO PERSON(PNAME, PAGE) VALUES('미영',24);

-- 전체조회
SELECT * FROM PERSON;

-- 나이가 4자리인 PERSON 데이터 추가
INSERT INTO PERSON VALUES('영수', 1111);

-- PERSON TABLE 삭제(삭제시 모든 데이터 삭제)
DROP TABLE PERSON;



-- 새로운 테이블 생성(나이 30 기본 설정)
CREATE TABLE PERSON(
	PNAME VARCHAR2(30),
	PAGE NUMBER(3) DEFAULT 30
);

INSERT INTO PERSON(PNAME) VALUES('철수');
INSERT INTO PERSON(PNAME) VALUES('창수');
INSERT INTO PERSON(PNAME) VALUES('지영');

-- 전체조회
SELECT * FROM PERSON;

-- PERSON 테이블 데이터 삭제
TRUNCATE TABLE PERSON;

-- 학생테이블 삭제
DROP TABLE STUDENT;
---------------------------------- 실습 ----------------------------
-- 학생테이블 생성
CREATE TABLE STUDENT(
	STD_NO CHAR(8) PRIMARY KEY, -- 기본키 설정
	STD_NAME VARCHAR2(30) NOT NULL, -- 데이터를 반드시 입력
	MAJOR_NAME VARCHAR2(30),
	-- 데이터가 안들어 왔을 때 0, NULL은 넣을 수 없음
	STD_SCORE NUMBER(3,2) DEFAULT 0 NOT NULL 
);

SELECT * FROM STUDENT;
------------------------------------------------------------------
-- 샘플데이터 5개
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('0001', '철수', '양성1반', 3.58);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0002', '영희', '양성2반', 3.75);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0003', '민수', '양성1반', 3.80);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0004', '지수', '양성3반', 3.90);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0005', '하늘', '양성2반', 3.65);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0006', '바다', '양성3반', 3.6);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0007', '호수', '양성1반', 3.85);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0008', '구름', '양성2반', 3.70);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0009', '별', '양성3반', 3.90);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0010', '해', '양성1반', 3.95);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0011', '달', '양성2반', 3.75);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0013', '산', '양성2반', 3.65);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0014', '강', '양성3반', 3.88);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0015', '바람', '양성1반', 3.70);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0016', '꽃', '양성2반', 3.95);

INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240002', '김철수', '전자 공학', 3.4);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240003', '이영희', '기계 공학', 3.6);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240004', '박민수', '경영학', 2.7);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240005', '최지훈', '경제학', 3.3);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240006', '김하늘', '물리학', 3.9);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240007', '박지수', '화학', 2.6);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240008', '유재석', '생명과학', 3.0);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240009', '강호동', '심리학', 3.5);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240010', '정준하', '철학', 3.2);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240011', '노홍철', '사회학', 3.9);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240012', '하하', '컴퓨터 공학', 3.5);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240013', '박명수', '전자 공학', 3.7);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240014', '이승기', '기계 공학', 2.5);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240015', '유희열', '생명과학', 3.8);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240016', '이상민', '철학', 3.0);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240017', '김구라', '물리학', 4.0);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240018', '김종국', '사회학', 2.9);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240019', '김희철', '경제학', 3.7);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240020', '장동민', '철학', 2.8);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240021', '김준호', '컴퓨터 공학', 4.1);



------------------------------------------------------------------------


INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('2024000', '김창수', '물리학', 3.9);

SELECT * FROM STUDENT;

------------------------------------------------------------------------

-- 학생 데이터 검색
SELECT * FROM STUDENT WHERE STD_NO ='20230001';
-- 연산자는 정확하게 일치하는 값을 검색할 때 사용
SELECT * FROM STUDENT WHERE STD_NO ='20240001';
-- LIKE 연산자는 패턴을 기반으로 데이터 검색을 할 때 사용
SELECT * FROM STUDENT WHERE STD_NO LIKE '2024000';
SELECT * FROM STUDENT WHERE STD_NO LIKE '2024% ';

-- 학생 데이터에서 평점 3.0이상인 학생출력
 SELECT * FROM STUDENT WHERE STD_SCORE >= 3.0;

------------------------------------------------------------------------

-- 테이블 컴럼 추가
ALTER TABLE STUDENT ADD STD_GENDER NUMBER(1) DEFAULT 0 NOT NULL;

-- 테이블 컴펌 변경
-- 이미 NOT NULL
ALTER TABLE STUDENT MODIFY STD_GENDER CHAR(1) DEFAULT 'M' NOT NULL;
-- 데이터를 비워야 함(0으로 이미 채워진 상태)
ALTER TABLE STUDENT MODIFY STD_GENDER CHAR(1) DEFAULT 'M';

ALTER TABLE STUDENT MODIFY STD_GENDER NUMBER(1) DEFAULT 0 NOT NULL;

UPDATE STUDENT SET STD_GENDER = NULL;

SELECT * FROM NEW_STUDENT;

-- 테이블 컬럼 삭제
ALTER TABLE STUDENT DROP COLUMN STD_GENDER;

-- 테이블 컬럼 이름 수정
ALTER TABLE STUDENT RENAME COLUMN STD_SCORE TO SCORE;

-- 테이블 이름 수정
ALTER TABLE STUDENT RENAME TO NEW_STUDENT;

-------------------------------------------------------

-- 날짜 컬럼 추가 및 데이터 추가
ALTER TABLE PERSON ADD BIRTH DATE;

-- PERSON 데이터 추가
INSERT INTO PERSON (PNAME, PAGE, BIRTH)
VALUES('김창수', 38, '1986-07-22');
INSERT INTO PERSON (PNAME, PAGE, BIRTH)
VALUES('정지영', 39, '1985-03-23');
INSERT INTO PERSON (PNAME, PAGE, BIRTH)
VALUES('김원광', 27, '1997-10-30');
INSERT INTO PERSON (PNAME, PAGE, BIRTH)
VALUES('이정옥', 63, '62-02-19');


SELECT * FROM PERSON;

-- 현재 날짜 시간 확인 방법
SELECT SYSDATE FROM DUAL;
