-- 학생 테이블 생성
-- 학번, 이름, 학과명, 평점
CREATE TABLE STUDENT(
<<<<<<< HEAD
	STD_NO CHAR(8), --()안에 있는 숫자 ; 8바이트
	STD_NAME VARCHAR2(50), -- 고정길이 문자열을 사용
	MAJOR_NAME VARCHAR2(50),
	STD_SCORE NUMBER(3,2) -- 숫자 3자리, 소수점 2자리까지 사용
	);
	
-- 데이터 추가
INSERT INTO STUDENT(STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES('20240001', '김창수', '기계설계', 3.55);

INSERT INTO STUDENT(STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES('20240002', '정지영', '건축설계', 3.85);

INSERT INTO STUDENT(STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES('20240003', '김철수', '컴퓨터공학', 3.25);

INSERT INTO STUDENT(STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES('20240004', '장미희', '산업디자인', 3.85);

-- 학생 테이블의 데이터 전체 조회
SELECT * FROM STUDENT;
-- 데이터 부분 조회(학번, 이름)
SELECT STD_NO, STD_NAME FROM STUDENT;


-- DDL ; DATA DEFINITION LANGUAGE ; 데이터 정의어 OR SQL 명령어
-- 테이블 생성
CREATE TABLE 테이블 이름(
	컴럼명1 테이터타입 [NULL | NOT NULL], -- NULL ; 입력 안해도 됨, NOT NULL ; 입력해야함
	컴럼명2 테이터타입 DEFAULT 기본값,
	컴럼명3 테이터타입 ,
	...
	CONSTRAINT 제약조건 이름 PRIMARY KEY(컬럼명) -- 주 식별자 설정시 사용
	-- 기본 키(Primary Key), 외래 키(Foreign Key) 자주 사용함
);

-- 데이터 타입
-- 문자열 ; char(2000바이트), varchar2(4000바이트), clob(128테라바이트)
-- 숫자열 ; number(자리수, 소수점 개수)최대 38자리, float(128)
-- 날짜 시간 ; date(날짜/시간), timestamp(소수점가지 저장 가능 최대 9자리)


-- PERSON 테이블
-- 이름 ; 문자열
-- 나이 ; 숫자
CREATE TABLE PERSON(
	PNAME VARCHAR2(30),
	PAGE NUMBER(3)
	
);
-- 데이터 5건 추가하는 sql문
INSERT INTO PERSON(PNAME, PAGE) VALUES('창수',38);
INSERT INTO PERSON(PNAME, PAGE) VALUES('지영',39);
INSERT INTO PERSON(PNAME, PAGE) VALUES('원광',28);
INSERT INTO PERSON(PNAME, PAGE) VALUES('철수',31);
INSERT INTO PERSON(PNAME, PAGE) VALUES('미영',24);

-- 전체조회
SELECT * FROM PERSON;

-- 나이가 4자리인 PERSON 데이터 추가
INSERT INTO PERSON VALUES('영수', 1111);

-- PERSON TABLE 삭제(삭제시 모든 데이터 삭제)
DROP TABLE PERSON;



-- 새로운 테이블 생성(나이 30 기본 설정)
=======
	STD_NO CHAR(8),
	STD_NAME VARCHAR2(50),
	MAJOR_NAME VARCHAR2(50),
	STD_SCORE NUMBER(3,2)
);
-- 데이터 추가
INSERT INTO 
STUDENT(STD_NO,STD_NAME,MAJOR_NAME,STD_SCORE)
VALUES('20203333','김첤후','컴퓨터공학과',3.24);

-- 학생 테이블의 데이터를 전체 조회
SELECT * FROM STUDENT;
SELECT STD_NO, STD_NAME FROM STUDENT;

-- DDL : Data Definition Language, 데이터 정의어
-- 	데이터베이스 구성요소를 정의, 변경, 삭제하는 사용됨
--	CREATE : 데이터베이스 구성 요소를 생성(테이블, 인덱스, 시퀸스, 사용자....) 
--	ALTER : 생성된 데이터베이스 구성 요소를 변경할 때 사용
--	DROP : 생성된 데이터베이스 구성 요소를 삭제할 때 사용
--	TRUNCATE : 테이블의 모든 데이터를 빠르게 삭제하고, 공간을 해제, 구조는 유지함

-- 테이블 생성
CREATE TABLE 테이블_이름(
	컬럼명1 데이터타입 [NULL | NOT NULL],
	컬럼명2 데이터타입 DEFAULT 기본값,
	컬럼명3 데이터타입,
	...
	CONSTRAINT 제약조건이름 PRIMARY KEY(컬럼명) 
);
CREATE TABLE 테이블_이름(
	컬럼명1 데이터타입 PRIMARY KEY,
	컬럼명2 데이터타입 DEFAULT 기본값,
	컬럼명3 데이터타입,
	...
);
-- 데이터 타입
-- 문자열 : CHAR(2000까지 지원), VARCHAR2(4000), CLOB(128TB)
-- 숫자 : NUMBER(자리수, 소수점개수) -> 최대 38, FLOAT(128)
-- 날짜 시간 : DATE(날짜/시간), TIMESTAMP(소수점까지 저장 가능 최대 9자리)

-- PERSON 테이블
-- 		이름 -> 문자열
--		나이 -> 숫자
CREATE TABLE PERSON(
	PNAME VARCHAR2(30),
	PAGE NUMBER(3)
);

--데이터 5건 넣는 SQL문
INSERT INTO PERSON(PNAME,PAGE) VALUES('John',25);
INSERT INTO PERSON(PNAME,PAGE) VALUES('Emma',30);
INSERT INTO PERSON(PNAME,PAGE) VALUES('Michael',40);
INSERT INTO PERSON(PNAME,PAGE) VALUES('Sophia',20);
--테이블에 모든 컬럼에 데이터를 저장, 테이블 생성시 작성한 컬럼 순서대로 데이터 작성
INSERT INTO PERSON VALUES('김철수',35);

--PERSON 테이블에 있는 모든 데이터를 조회
SELECT * FROM PERSON;

--나이가 4자리인 PERSON 데이터 추가
INSERT INTO PERSON VALUES('김철수',3500);

--PERSON 테이블 삭제 구문 --> 삭제시 모든 데이터가 날아간다.
DROP TABLE PERSON;

--컬럼에 기본값 설정
>>>>>>> 7d0ff4ad28367fb6cd73e0a8254a78e055306333
CREATE TABLE PERSON(
	PNAME VARCHAR2(30),
	PAGE NUMBER(3) DEFAULT 30
);
<<<<<<< HEAD

INSERT INTO PERSON(PNAME) VALUES('철수');
INSERT INTO PERSON(PNAME) VALUES('창수');
INSERT INTO PERSON(PNAME) VALUES('지영');

-- 전체조회
SELECT * FROM PERSON;

-- PERSON 테이블 데이터 삭제
TRUNCATE TABLE PERSON;

-- 학생테이블 삭제
DROP TABLE STUDENT;
---------------------------------- 실습 ----------------------------
-- 학생테이블 생성
CREATE TABLE STUDENT(
	STD_NO CHAR(8) PRIMARY KEY, -- 기본키 설정
	STD_NAME VARCHAR2(30) NOT NULL, -- 데이터를 반드시 입력
	MAJOR_NAME VARCHAR2(30),
	-- 데이터가 안들어 왔을 때 0, NULL은 넣을 수 없음
	STD_SCORE NUMBER(3,2) DEFAULT 0 NOT NULL 
);

SELECT * FROM STUDENT;
------------------------------------------------------------------
-- 샘플데이터 5개
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('0001', '철수', '양성1반', 3.58);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0002', '영희', '양성2반', 3.75);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0003', '민수', '양성1반', 3.80);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0004', '지수', '양성3반', 3.90);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0005', '하늘', '양성2반', 3.65);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0006', '바다', '양성3반', 3.6);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0007', '호수', '양성1반', 3.85);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0008', '구름', '양성2반', 3.70);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0009', '별', '양성3반', 3.90);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0010', '해', '양성1반', 3.95);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0011', '달', '양성2반', 3.75);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0013', '산', '양성2반', 3.65);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0014', '강', '양성3반', 3.88);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0015', '바람', '양성1반', 3.70);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('0016', '꽃', '양성2반', 3.95);

INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240002', '김철수', '전자 공학', 3.4);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240003', '이영희', '기계 공학', 3.6);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240004', '박민수', '경영학', 2.7);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240005', '최지훈', '경제학', 3.3);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240006', '김하늘', '물리학', 3.9);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240007', '박지수', '화학', 2.6);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240008', '유재석', '생명과학', 3.0);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240009', '강호동', '심리학', 3.5);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240010', '정준하', '철학', 3.2);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240011', '노홍철', '사회학', 3.9);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240012', '하하', '컴퓨터 공학', 3.5);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240013', '박명수', '전자 공학', 3.7);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240014', '이승기', '기계 공학', 2.5);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240015', '유희열', '생명과학', 3.8);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240016', '이상민', '철학', 3.0);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240017', '김구라', '물리학', 4.0);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240018', '김종국', '사회학', 2.9);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240019', '김희철', '경제학', 3.7);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240020', '장동민', '철학', 2.8);
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('20240021', '김준호', '컴퓨터 공학', 4.1);



------------------------------------------------------------------------


INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE)
VALUES ('2024000', '김창수', '물리학', 3.9);

SELECT * FROM STUDENT;

------------------------------------------------------------------------

-- 학생 데이터 검색
SELECT * FROM STUDENT WHERE STD_NO ='20230001';
-- 연산자는 정확하게 일치하는 값을 검색할 때 사용
SELECT * FROM STUDENT WHERE STD_NO ='20240001';
-- LIKE 연산자는 패턴을 기반으로 데이터 검색을 할 때 사용
SELECT * FROM STUDENT WHERE STD_NO LIKE '2024000';
SELECT * FROM STUDENT WHERE STD_NO LIKE '2024% ';

-- 학생 데이터에서 평점 3.0이상인 학생출력
 SELECT * FROM STUDENT WHERE STD_SCORE >= 3.0;

------------------------------------------------------------------------

-- 테이블 컴럼 추가
ALTER TABLE STUDENT ADD STD_GENDER NUMBER(1) DEFAULT 0 NOT NULL;

-- 테이블 컴펌 변경
-- 이미 NOT NULL
ALTER TABLE STUDENT MODIFY STD_GENDER CHAR(1) DEFAULT 'M' NOT NULL;
-- 데이터를 비워야 함(0으로 이미 채워진 상태)
ALTER TABLE STUDENT MODIFY STD_GENDER CHAR(1) DEFAULT 'M';

ALTER TABLE STUDENT MODIFY STD_GENDER NUMBER(1) DEFAULT 0 NOT NULL;

UPDATE STUDENT SET STD_GENDER = NULL;

SELECT * FROM NEW_STUDENT;

-- 테이블 컬럼 삭제
ALTER TABLE STUDENT DROP COLUMN STD_GENDER;

-- 테이블 컬럼 이름 수정
ALTER TABLE STUDENT RENAME COLUMN STD_SCORE TO SCORE;

-- 테이블 이름 수정
ALTER TABLE STUDENT RENAME TO NEW_STUDENT;

-------------------------------------------------------

-- 날짜 컬럼 추가 및 데이터 추가
ALTER TABLE PERSON ADD BIRTH DATE;

-- PERSON 데이터 추가
INSERT INTO PERSON (PNAME, PAGE, BIRTH)
VALUES('김창수', 38, '1986-07-22');
INSERT INTO PERSON (PNAME, PAGE, BIRTH)
VALUES('정지영', 39, '1985-03-23');
INSERT INTO PERSON (PNAME, PAGE, BIRTH)
VALUES('김원광', 27, '1997-10-30');
INSERT INTO PERSON (PNAME, PAGE, BIRTH)
VALUES('이정옥', 63, '62-02-19');


SELECT * FROM PERSON;

-- 현재 날짜 시간 확인 방법
SELECT SYSDATE FROM DUAL;
=======
--PAGE에 데이터를 않넣었기 때문에 기본값 지정한 30이 저장됨
INSERT INTO PERSON(PNAME) VALUES('김철수');
INSERT INTO PERSON(PNAME, PAGE) VALUES('김철수', NULL);

--PERSON 테이블 데이터 삭제
TRUNCATE TABLE PERSON;

--학생 테이블 삭제
DROP TABLE STUDENT;

--학생 테이블
-- 학번, 이름, 학과명, 평점
CREATE TABLE STUDENT(
	STD_NO CHAR(8) PRIMARY KEY, --기본키 설정을 할때
	STD_NAME VARCHAR2(30) NOT NULL, --데이터를 반드시 입력을 받아야할 때
	MAJOR_NAME VARCHAR2(30),
	--데이터가 안들어 왔을때 기본값 0으로 설정, NULL이 올 수 없게끔 처리
	STD_SCORE NUMBER(3,2) DEFAULT 0 NOT NULL  
);
DROP TABLE STUDENT;
--학생 데이터 5건 저장
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('20240001', '홍길동', '컴퓨터 공학', 3.5);
--NOT NULL에 데이터를 않넣은 경우
INSERT INTO STUDENT (STD_NO, MAJOR_NAME, STD_SCORE) 
VALUES ('20240002', '컴퓨터 공학', 3.5);
--DEFAULT와 NOT NULL이 지정된 곳에 데이터를 않넣었을때
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME) 
VALUES ('20240002', '김영희', '컴퓨터 공학');
--DEFAULT와 NOT NULL이 있으면 데이터를 넣지않으면 기본값이 저장
--단, NULL 값을 직접 저장할려고하면 안됨
INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('20240003', '김영희', '컴퓨터 공학', NULL);

INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('20240003', '이영희', '기계 공학', 4.0);

INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('20240004', '박민수', '경영학', 2.8);

INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('20240005', '최지훈', '경제학', 3.2);

INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('20240006', '정수진', '물리학', 3.9);

INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('20240007', '김하늘', '화학', 2.5);

INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('20240008', '이준호', '생명과학', 3.1);

INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('20240009', '김다은', '심리학', 3.8);

INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('20240010', '오지민', '철학', 3.0);

INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('20240011', '서현우', '사회학', 2.9);

INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('20240012', '한소라', '컴퓨터 공학', 4.1);

INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('20240013', '박서준', '전자 공학', 3.4);

INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('20240014', '이지은', '기계 공학', 3.6);

INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('20240015', '한지민', '경영학', 2.7);

INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('20240016', '김민재', '경제학', 3.3);

INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('20240017', '이정민', '물리학', 3.9);

INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('20240018', '정호연', '화학', 2.6);

INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('20240019', '최예진', '생명과학', 3.0);

INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('20240020', '박준영', '심리학', 3.5);

INSERT INTO STUDENT (STD_NO, STD_NAME, MAJOR_NAME, STD_SCORE) 
VALUES ('2024000', '이영수', '물리학', 2.9);

--학생 데이터 검색
SELECT * FROM STUDENT WHERE STD_NO = '20230001';
SELECT * FROM STUDENT WHERE STD_NO = '2024000';
--CHAR 고정길이 문자열이라서 공간이 남으면 뒤에 공백으로 채움
SELECT * FROM STUDENT WHERE STD_NO LIKE '2024000';
SELECT * FROM STUDENT WHERE STD_NO LIKE '2024000 ';
--평점이 3.0 이상인 데이만 조회
SELECT * FROM STUDENT WHERE STD_SCORE >= 3.0;

--테이블 컬럼 추가
ALTER TABLE STUDENT ADD STD_GENDER NUMBER(1) DEFAULT 0 NOT NULL;

--테이블 컬럼을 변경
ALTER TABLE STUDENT 
MODIFY STD_GENDER CHAR(1) DEFAULT 'M' NOT NULL;
ALTER TABLE STUDENT 
MODIFY STD_GENDER CHAR(1) DEFAULT 'M';
ALTER TABLE STUDENT MODIFY STD_GENDER NUMBER(1) DEFAULT 0 NULL;

UPDATE STUDENT SET STD_GENDER = NULL;

--테이블 컬럼 삭제
ALTER TABLE STUDENT DROP COLUMN STD_GENDER; 

--테이블 컬럼 이름 변경
ALTER TABLE STUDENT RENAME COLUMN STD_NAME TO STD_NEW_NAME;

--테이블 이름 변경
ALTER TABLE STUDENT RENAME TO NEW_STUDENT;

--날짜 컬럼 추가 및 데이터 추가
ALTER TABLE PERSON ADD BIRTH DATE;

--PERSON 데이터 추가
INSERT INTO PERSON(PNAME, PAGE, BIRTH)
VALUES('박명운', 22, '1999-04-29');
INSERT INTO PERSON(PNAME, PAGE, BIRTH)
VALUES('박명운', 22, '1999/04/29');
INSERT INTO PERSON(PNAME, PAGE, BIRTH)
VALUES('박명운', 22, '99/04/29');

SELECT * FROM PERSON;

--현재 날짜 시간 확인 방법
SELECT SYSDATE FROM DUAL;

INSERT INTO PERSON(PNAME, PAGE, BIRTH)
VALUES('박명운', 22, SYSDATE);






>>>>>>> 7d0ff4ad28367fb6cd73e0a8254a78e055306333
